### BASH ALIASES ###
#alias sup='sudo apt update -y && sudo apt upgrade -y && sudo flatpak update -y && sudo snap refresh && sudo apt autoremove -y && sudo apt full-upgrade -y'
#alias sudo='doas'
alias c='clear'
alias lx='ls -alhF --color=auto --format=long --group-directories-first -N'
alias la='ls -al'
alias ipip='echo ; hostname -I && curl ipinfo.io/ip ; echo ; echo'
alias ping='ping -c 9'
alias speed='echo ; speedtest-cli --server 6825 ; echo'
alias df='df -h'
alias grep="grep --color='auto'"
alias spo='systemctl poweroff'
alias srb='systemctl reboot'
#alias out='~/.config/polybar/logout.sh'
alias nf='neofetch'
#alias vim='nvim'
alias v='nvim'
alias ytdla="youtube-dl -x -f 'bestaudio[ext=mp3]'"
alias ytdlv='youtube-dl -i'
alias kup='curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin'
alias ..='cd ..'
alias mirrors='sudo nvim /etc/pacman.d/mirrorlist'
alias update='sudo pacman -Syu --disable-download-timeout --noconfirm'
alias feh='feh -Tfeht'
alias ftpin='cd ~/public_html/basep/update-source/'
alias upup='yay && $HOME/.config/polybar/launch2.sh &'
